name: php
uses: franzliedke/gh-action-php@0.3.0
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs: "php8.1 vendor/bin/phpunit"
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
}
